sen0140_node:
  ros__parameters:

    # I2C
    i2c_device: "/dev/i2c-1"

    # -------------------------------------------------
    # IMU
    # -------------------------------------------------

    imu:
      frame_id: "imu_link"

    # ADXL345 accelerometer
    accel:
      address: 83 # 0x53
      odr: 200

      # 0 = +/-2 g
      # 1 = +/-4 g
      # 2 = +/-8 g
      # 3 = +/-16 g
      range: 3

    # ITG-3200 gyroscope
    gyro:
      address: 104 # 0x68
      rate: 200

      # DLPF configuration:
      # 0 = 256 Hz
      # 1 = 188 Hz
      # 2 = 98 Hz
      # 3 = 42 Hz
      # 4 = 20 Hz
      # 5 = 10 Hz
      # 6 = 5 Hz
      dlpf: 2

    # -------------------------------------------------
    # Magnetometer
    # -------------------------------------------------

    mag:
      address: 12 # 0x0C
      frame_id: "imu_link"

      # VCM5883L output data rate
      odr: 50

    # -------------------------------------------------
    # Barometer
    # -------------------------------------------------

    baro:
      address: 119 # 0x77
      frame_id: "imu_link"

      # ROS polling / publication rate
      rate: 10.0

      # BMP280 oversampling settings
      temp_oversampling: 2
      pressure_oversampling: 5